baseURL = "https://timelyrain.top/"
# baseURL = "/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Winter"                       # site title                     # 网站标题
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 5                           # shows the number of articles   # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                   # your google analytics id       # Google统计代码
disqusShortname = ""                   # your discuss shortname         # Disqus评论系统代码

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]                               # essential                      # 必需
  name = "VarKai"

[blackfriday]
  smartypants = false

[[menu.main]]                          # config your menu               # 配置菜单
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "关于"
  weight = 40
  identifier = "about"
  url = "/about/"

[params]
  subTitle = "兼听则明，偏信则暗"                                        # site's subTitle              # 网站二级标题
  footerSlogan = "寻找 Coding 的乐趣"                                   # site's footer slogan         # 网站页脚标语
  keywords = ["huer","hueralin","blog","timelyrain","fe","FE"]         # site's keywords              # 网站关键字
  description = "hueralin' blog"                                       # site's description           # 网站描述
  enableMathJax = false                                                # enable mathjax               # 是否使用mathjax（数学公式）
  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  mainSections = ["posts","post"]

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
# [params.valine]
#   enable = false
#   appId = ""
#   appKey = ""
#   placeholder = " "
#   visitor = true

[params.utteranc]
  enable = true
  repo = "hueralin/blog"
  issueTerm = "title"
  theme = "github-light"

# Your socail's url
# 社交地址配置
[social]
  github = "https://github.com/hueralin"
#   twitter = " "
#   facebook = " "
#   weibo = " "
#   instagram = " "

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
